<a href="https://colab.research.google.com/github/yuanhsinliao/Machine-Learning-Prediction---News-Headline-Category/blob/main/News_category.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("/content/drive/MyDrive/Dataset /News Category (Text).csv")

In [7]:
X = df["headline"]
Y = df["category"]

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
X_cv = CountVectorizer().fit_transform(X)

In [10]:
X_cv.shape

(6864, 10045)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X_cv, Y)

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
from sklearn import linear_model

In [15]:
model = linear_model.LogisticRegression()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[944  23]
 [ 72 677]]
accuracy is  0.9446386946386947


In [16]:
from sklearn import ensemble

In [17]:
model = ensemble.RandomForestClassifier()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[946  21]
 [ 97 652]]
accuracy is  0.9312354312354313


In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
X_tfidf = TfidfVectorizer().fit_transform(X)

In [20]:
X_train,X_test,Y_train,Y_test = train_test_split(X_tfidf, Y)

In [21]:
model = linear_model.LogisticRegression()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[1010   19]
 [  61  626]]
accuracy is  0.9533799533799534


In [22]:
model = ensemble.RandomForestClassifier()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[1006   23]
 [  82  605]]
accuracy is  0.9388111888111889


In [23]:
pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.5/156.5 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 53.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 76.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 50.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 17.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━

In [24]:
from sentence_transformers import SentenceTransformer

In [25]:
model = SentenceTransformer("bert-base-nli-mean-tokens")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.99k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [26]:
X_bert = model.encode(X)

In [27]:
X_bert.shape

(6864, 768)

In [28]:
X_cv

<6864x10045 sparse matrix of type '<class 'numpy.int64'>'
	with 67291 stored elements in Compressed Sparse Row format>

In [29]:
X_tfidf

<6864x10045 sparse matrix of type '<class 'numpy.float64'>'
	with 67291 stored elements in Compressed Sparse Row format>

In [30]:
X_train,X_test,Y_train,Y_test = train_test_split(X_bert, Y)

In [31]:
model = linear_model.LogisticRegression(max_iter=2000)
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[983  40]
 [ 34 659]]
accuracy is  0.9568764568764568


In [32]:
model = ensemble.RandomForestClassifier()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[995  28]
 [ 73 620]]
accuracy is  0.9411421911421911


In [33]:
model = ensemble.GradientBoostingClassifier()
model.fit(X_train,Y_train)
pred = model.predict(X_test)
cm = confusion_matrix(Y_test,pred)
print(cm)
print("accuracy is ", (cm[0,0]+cm[1,1])/(sum(sum(cm))))

[[984  39]
 [ 57 636]]
accuracy is  0.9440559440559441
